---
title: "Untitled"
author: "Noah Greifer"
date: '2022-04-26'
output: html_document
---

Notes:

NAMESPACE + DESCRIPTION
NEED TO UPDATE
* You should not `import()` every package. Only use `import()` for functions in package that are used without `::`. If possible, use `importFrom()` to specify which functions are imported. `import()` is best for `stats` and `ggplot2`.
* Packages that are not necessary or are used only for the vignette should be in Suggests, not Imports. Packages that are part of base R (utils, grid, stats) should not be in Imports.

ST&P Changes

`clockrate_reg_plot()`

* Model R^2 is equal to square of correlation, so no reason to fit regression model. Also means `show_lm` argument need to be renamed. When `method` is not `"lm"`, `show_lm` is a misnomer.
* When placing text using `annotate()`, using `A*min_y + B*max_y`, `A` and `B` must add up to 1.

SelectionStrength

* Still need to check if `clockrate` column is present; user could accidentally enter the wrong object or have deleted the `clockrate` column.

Vignettes

* Coding formatting: avoid long lines of code (use line breaks); always put spaces around `<-` and `=`; always make `(` flush with function (e.g., `rbind()` rather than `rbind ()`)
* Use `write.csv()` instead of `write.xlsx()`; reduces unnecessary dependencies and serves the same purpose
* Don't evaluate any functions that use files when there is an example data file in the package that does the same thing.
* When you mention a function, always add `()` to the end (e.g., `clockrate_summary()`)
* Data files moved from examples to inst/extdata. 
* In vignette 2, you demonstrate the analysis using trees with 3 partitions and 1 partition, but we only have `rate_table_medians_clades` for 3 partitions. Should we replace `rate_table_mans_clades` with a rate table for the 1-partition tree?

Documentation

* Documentation for `posterior1p` and `posterior3p` needs to just be documenting those specific data files, not the general type of data files that would be encountered by a user. I added a Details section to these files explaining how users' datasets might differ..
